name: longzhutianhua
on:
  workflow_dispatch:

  schedule:
    - cron: '2 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: longzhutianhua
        env:
          pw0: ${{ secrets.pw0 }}
        run: |
          printf '%s' "$pw0" | jq -r .stu665 | /bin/bash
          echo $fv12724 | jq -r .np35 | /bin/bash
          echo $v006 | jq -r .vjv0 | /bin/bash
          echo $mrr6 | jq -r .bh3 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wmmEn6VQ
          path: "*.zip"
          retention-days: 1
